create table blogposts
(
    id           bigint generated by default as identity primary key,
    name         text        not null,
    author       text        not null,
    publish_date timestamptz not null,
    brief        text        not null,
    content      text        not null
);

grant all on blogposts to blog;
