[package]
name = "steg"
version = "0.1.0"
edition = "2021"
default-run = "steg"

[[bin]]
name = "steg"
path = "src/steg/bin/main.rs"

[[bin]]
name = "bodo"
path = "src/bodo/bin/main.rs"

[dependencies]
zip = "0.5.13"
xml-rs = "0.8"
